package de.visualdigits.kaudiotagger.model.tag

import org.slf4j.LoggerFactory
import java.nio.ByteBuffer

abstract class AbstractTagItem {

    val log = LoggerFactory.getLogger(javaClass)

    constructor()

    constructor(copyObject: AbstractTagItem?) {
        // no copy constructor in super class
    }

    /**
     * ID string that usually corresponds to the class name, but can be
     * displayed to the user. It is not indended to identify each individual
     * instance.
     *
     * @return ID string
     */
    abstract fun getIdentifier(): String?

    /**
     * Return size of this item
     *
     * @return size of this item
     */
    abstract fun getSize(): Int

    /**
     * @param byteBuffer file to read from
     * @throws TagException on any exception generated by this library.
     */
    abstract fun read(byteBuffer: ByteBuffer?)

    /**
     * Returns true if this datatype is a subset of the argument. This instance
     * is a subset if it is the same class as the argument.
     *
     * @param obj datatype to determine subset of
     * @return true if this instance and its entire datatype array list is a
     * subset of the argument.
     */
    open fun isSubsetOf(obj: Any?): Boolean {
        return obj is AbstractTagItem
    }

    /**
     * Returns true if this datatype and its body equals the argument and its
     * body. this datatype is equal if and only if they are the same class
     *
     * @param obj datatype to determine equality of
     * @return true if this datatype and its body are equal
     */
    override fun equals(obj: Any?): Boolean {
        if (this === obj) {
            return true
        }
        return obj is AbstractTagItem
    }
}