package de.visualdigits.kaudiotagger.model.audiofile.mp3

import de.visualdigits.kaudiotagger.model.audiofile.AudioFile
import de.visualdigits.kaudiotagger.model.audiofile.header.mp3.MP3AudioHeader
import de.visualdigits.kaudiotagger.model.exceptions.InvalidAudioFrameException
import de.visualdigits.kaudiotagger.model.exceptions.TagException
import de.visualdigits.kaudiotagger.model.exceptions.TagNotFoundException
import de.visualdigits.kaudiotagger.model.tag.AbstractTag
import de.visualdigits.kaudiotagger.model.tag.Tag
import de.visualdigits.kaudiotagger.model.tag.id3.AbstractID3v2Tag
import de.visualdigits.kaudiotagger.model.tag.id3.ID3v11Tag
import de.visualdigits.kaudiotagger.model.tag.id3.ID3v1Tag
import de.visualdigits.kaudiotagger.model.tag.id3.ID3v22Tag
import de.visualdigits.kaudiotagger.model.tag.id3.ID3v23Tag
import de.visualdigits.kaudiotagger.model.tag.id3.ID3v24Tag
import de.visualdigits.kaudiotagger.model.tag.lyrics3.AbstractLyrics3
import de.visualdigits.kaudiotagger.util.AbstractTagDisplayFormatter
import de.visualdigits.kaudiotagger.util.ErrorMessage
import de.visualdigits.kaudiotagger.util.PlainTextTagDisplayFormatter
import de.visualdigits.kaudiotagger.util.TagOptionSingleton
import de.visualdigits.kaudiotagger.util.XMLTagDisplayFormatter
import java.io.File
import java.io.FileInputStream
import java.io.FileNotFoundException
import java.io.FileOutputStream
import java.io.IOException
import java.io.InputStream
import java.io.RandomAccessFile
import java.lang.reflect.InvocationTargetException
import java.nio.ByteBuffer
import java.nio.channels.FileChannel
import java.security.MessageDigest

/**
 * This class represents a physical MP3 File
 */
class MP3File : AudioFile {

    companion object {

        /* Load id3v1tag if exists */
        const val LOAD_IDV1TAG: Int = 2

        /* Load id3v2tag if exists */
        const val LOAD_IDV2TAG: Int = 4

        /**
         * This option is currently ignored
         */
        const val LOAD_LYRICS3: Int = 8
        val LOAD_ALL: Int = LOAD_IDV1TAG or LOAD_IDV2TAG or LOAD_LYRICS3
        private const val MINIMUM_FILESIZE = 150
        var tagFormatter: AbstractTagDisplayFormatter? = null

        private fun createXMLStructureFormatter() {
            tagFormatter = XMLTagDisplayFormatter()
        }

        private fun createPlainTextStructureFormatter() {
            tagFormatter = PlainTextTagDisplayFormatter()
        }
    }

    /**
     * The Lyrics3 tag that this file contains.
     */
    private val lyrics3tag: AbstractLyrics3? = null

    /**
     * the ID3v2 tag that this file contains.
     */
    private var id3v2tag: AbstractID3v2Tag? = null

    /**
     * Representation of the idv2 tag as a idv24 tag
     */
    private var id3v2Asv24tag: ID3v24Tag? = null

    /**
     * Representation of the idv2 tag as a idv24 tag
     */
    private var id3v2tagAsv24: ID3v24Tag? = null

    /**
     * The ID3v1 tag that this file contains.
     */
    private var id3v1tag: ID3v1Tag? = null

    /**
     * Creates a new empty MP3File datatype that is not associated with a
     * specific file.
     */
    constructor()

    /**
     * Creates a new MP3File datatype and parse the tag from the given filename.
     *
     * @param filename MP3 file
     * @throws IOException                                                  on any I/O error
     * @throws TagException                                                 on any exception generated by this library.
     * @throws org.jaudiotagger.audio.exceptions.ReadOnlyFileException
     * @throws InvalidAudioFrameException
     */
    constructor(filename: String) : this(File(filename))

    /**
     * Creates a new MP3File dataType and parse the tag from the given file
     * Object, files can be opened read only if required.
     *
     * @param file        MP3 file
     * @param loadOptions decide what tags to load
     * @param readOnly    causes the files to be opened readonly
     * @throws IOException                                                  on any I/O error
     * @throws TagException                                                 on any exception generated by this library.
     * @throws org.jaudiotagger.audio.exceptions.ReadOnlyFileException
     * @throws InvalidAudioFrameException
     */
    /**
     * Creates a new MP3File dataType and parse the tag from the given file
     * Object, files must be writable to use this constructor.
     *
     * @param file        MP3 file
     * @param loadOptions decide what tags to load
     * @throws IOException                                                  on any I/O error
     * @throws TagException                                                 on any exception generated by this library.
     * @throws org.jaudiotagger.audio.exceptions.ReadOnlyFileException
     * @throws InvalidAudioFrameException
     */
    /**
     * Creates a new MP3File datatype and parse the tag from the given file
     * Object.
     *
     * @param file MP3 file
     * @throws IOException                                                  on any I/O error
     * @throws TagException                                                 on any exception generated by this library.
     * @throws org.jaudiotagger.audio.exceptions.ReadOnlyFileException
     * @throws InvalidAudioFrameException
     */
    @JvmOverloads
    constructor(file: File, loadOptions: Int = LOAD_ALL, readOnly: Boolean = false) {
        var newFile: RandomAccessFile? = null
        try {
            this.file = file

            //Check File accessibility
            newFile = checkFilePermissions(file, readOnly)

            //Read ID3v2 tag size (if tag exists) to allow audioHeader parsing to skip over tag
            val tagSizeReportedByHeader = AbstractID3v2Tag.getV2TagSizeIfExists(
                file
            )
            log.debug("TagHeaderSize:" + tagSizeReportedByHeader.toHexString())
            audioHeader = MP3AudioHeader(file, tagSizeReportedByHeader)

            //If the audio header is not straight after the end of the tag then search from start of file
            if (tagSizeReportedByHeader !=
                (audioHeader as MP3AudioHeader).mp3StartByte
            ) {
                log.debug("First header found after tag:$audioHeader")
                audioHeader = checkAudioStart(
                    tagSizeReportedByHeader,
                    (audioHeader as MP3AudioHeader)
                )
            }

            //Read v1 tags (if any)
            readV1Tag(file, newFile, loadOptions)

            //Read v2 tags (if any)
            readV2Tag(
                file,
                loadOptions,
                (audioHeader as MP3AudioHeader).mp3StartByte.toInt()
            )

            //If we have a v2 tag use that, if we do not but have v1 tag use that
            //otherwise use nothing
            //TODO:if have both should we merge
            //rather than just returning specific ID3v22 tag, would it be better to return v24 version ?
            if (this.id3v2tag != null) {
                setTag(this.id3v2tag)
            } else if (id3v1tag != null) {
                setTag(id3v1tag)
            }
        } finally {
            if (newFile != null) {
                newFile.close()
            }
        }
    }

    /**
     * Read v1 tag
     *
     * @param file
     * @param newFile
     * @param loadOptions
     * @throws IOException
     */
    private fun readV1Tag(file: File?, newFile: RandomAccessFile, loadOptions: Int) {
        if ((loadOptions and LOAD_IDV1TAG) != 0) {
            log.debug("Attempting to read id3v1tags")
            try {
                id3v1tag = ID3v11Tag(newFile)
            } catch (ex: TagNotFoundException) {
                log.debug("No ids3v11 tag found")
            }

            try {
                if (id3v1tag == null) {
                    id3v1tag = ID3v1Tag(newFile)
                }
            } catch (ex: TagNotFoundException) {
                log.debug("No id3v1 tag found")
            }
        }
    }

    /**
     * Read V2tag if exists
     *
     *
     * TODO:shouldn't we be handing TagExceptions:when will they be thrown
     *
     * @param file
     * @param loadOptions
     * @throws IOException
     * @throws TagException
     */
    private fun readV2Tag(file: File, loadOptions: Int, startByte: Int) {
        //We know where the actual Audio starts so load all the file from start to that point into
        //a buffer then we can read the IDv2 information without needing any more File I/O
        if (startByte >= AbstractID3v2Tag.TAG_HEADER_LENGTH) {
            log.debug("Attempting to read id3v2tags")
            var fis: FileInputStream? = null
            var fc: FileChannel? = null
            var bb: ByteBuffer?
            try {
                fis = FileInputStream(file)
                fc = fis.getChannel()
                bb = ByteBuffer.allocate(startByte)
                // XXX: don't change it to map
                // https://stackoverflow.com/questions/28378713/bytebuffer-getbyte-int-int-failed-on-android-ics-and-jb
                fc.read(bb, 0)
            } finally {
                if (fc != null) {
                    fc.close()
                }

                if (fis != null) {
                    fis.close()
                }
            }

            try {
                bb.rewind()

                if ((loadOptions and LOAD_IDV2TAG) != 0) {
                    log.debug("Attempting to read id3v2tags")
                    try {
                        this.setid3v2tag(ID3v24Tag(bb))
                    } catch (ex: TagNotFoundException) {
                        log.debug("No id3v24 tag found")
                    }

                    try {
                        if (id3v2tag == null) {
                            this.setid3v2tag(ID3v23Tag(bb))
                        }
                    } catch (ex: TagNotFoundException) {
                        log.debug("No id3v23 tag found")
                    }

                    try {
                        if (id3v2tag == null) {
                            this.setid3v2tag(ID3v22Tag(bb))
                        }
                    } catch (ex: TagNotFoundException) {
                        log.debug("No id3v22 tag found")
                    }
                }
            } finally {
                //Workaround for 4724038 on Windows
                bb.clear()
                if (bb.isDirect()) {
                    // Reflection substitute for following code:
                    //    ((sun.nio.ch.DirectBuffer) bb).cleaner().clean();
                    // which causes exception on Android - Sun NIO classes are not available
                    try {
                        val clazz = Class.forName("sun.nio.ch.DirectBuffer")
                        val cleanerMethod = clazz.getMethod("cleaner")
                        val cleaner = cleanerMethod.invoke(bb) // cleaner = bb.cleaner()
                        if (cleaner != null) {
                            val cleanMethod = cleaner.javaClass.getMethod("clean")
                            cleanMethod.invoke(cleaner) // cleaner.clean()
                        }
                    } catch (e: ClassNotFoundException) {
                        log.error("Could not load sun.nio.ch.DirectBuffer.")
                    } catch (e: NoSuchMethodException) {
                        log.error(
                            "Could not invoke DirectBuffer method - " + e.message
                        )
                    } catch (e: InvocationTargetException) {
                        log.error(
                            "Could not invoke DirectBuffer method - target exception"
                        )
                    } catch (e: IllegalAccessException) {
                        log.error(
                            "Could not invoke DirectBuffer method - illegal access"
                        )
                    }
                }
            }
        } else {
            log.debug("Not enough room for valid id3v2 tag:" + startByte)
        }
    }

    /**
     * Regets the audio header starting from start of file, and write appropriate logging to indicate
     * potential problem to user.
     *
     * @param startByte
     * @param firstHeaderAfterTag
     * @return
     * @throws IOException
     * @throws InvalidAudioFrameException
     */
    private fun checkAudioStart(
        startByte: Long,
        firstHeaderAfterTag: MP3AudioHeader
    ): MP3AudioHeader {
        val headerOne: MP3AudioHeader
        val headerTwo: MP3AudioHeader?

        log.warn(
            ErrorMessage.MP3_ID3TAG_LENGTH_INCORRECT.getMsg(
                file?.getPath(),
                startByte.toHexString(),
                firstHeaderAfterTag.mp3StartByte.toHexString()
            )
        )

        //because we cant agree on start location we reread the audioheader from the start of the file, at least
        //this way we cant overwrite the audio although we might overwrite part of the tag if we write this file
        //back later
        headerOne = MP3AudioHeader(file, 0)
        log.debug("Checking from start:" + headerOne)

        //Although the id3 tag size appears to be incorrect at least we have found the same location for the start
        //of audio whether we start searching from start of file or at the end of the alleged of file so no real
        //problem
        if (firstHeaderAfterTag.mp3StartByte == headerOne.mp3StartByte) {
            log.debug(
                ErrorMessage.MP3_START_OF_AUDIO_CONFIRMED.getMsg(
                    file?.getPath(),
                    headerOne.mp3StartByte.toHexString()
                )
            )
            return firstHeaderAfterTag
        } else {
            //We get a different value if read from start, can't guarantee 100% correct lets do some more checks
            log.debug(
                (ErrorMessage.MP3_RECALCULATED_POSSIBLE_START_OF_MP3_AUDIO.getMsg(
                    file?.getPath(),
                    headerOne.mp3StartByte.toHexString()
                ))
            )

            //Same frame count so probably both audio headers with newAudioHeader being the first one
            if (firstHeaderAfterTag.numberOfFrames == headerOne.numberOfFrames
            ) {
                log.warn(
                    (ErrorMessage.MP3_RECALCULATED_START_OF_MP3_AUDIO.getMsg(
                        file?.getPath(),
                        headerOne.mp3StartByte.toHexString()
                    ))
                )
                return headerOne
            }

            //If the size reported by the tag header is a little short and there is only nulls between the recorded value
            //and the start of the first audio found then we stick with the original header as more likely that currentHeader
            //DataInputStream not really a header
            if (isFilePortionNull(
                    startByte.toInt(),
                    firstHeaderAfterTag.mp3StartByte.toInt()
                )
            ) {
                return firstHeaderAfterTag
            }

            //Skip to the next header (header 2, counting from start of file)
            headerTwo = MP3AudioHeader(
                file,
                headerOne.mp3StartByte + (headerOne.mp3FrameHeader?.getFrameLength()?:0)
            )

            //It matches the header we found when doing the original search from after the ID3Tag therefore it
            //seems that newAudioHeader was a false match and the original header was correct
            if (headerTwo.mp3StartByte == firstHeaderAfterTag.mp3StartByte) {
                log.warn(
                    (ErrorMessage.MP3_START_OF_AUDIO_CONFIRMED.getMsg(
                        file?.getPath(),
                        firstHeaderAfterTag.mp3StartByte.toHexString()
                    ))
                )
                return firstHeaderAfterTag
            }

            //It matches the frameCount the header we just found so lends weight to the fact that the audio does indeed start at new header
            //however it maybe that neither are really headers and just contain the same data being misrepresented as headers.
            if (headerTwo.numberOfFrames == headerOne.numberOfFrames) {
                log.warn(
                    (ErrorMessage.MP3_RECALCULATED_START_OF_MP3_AUDIO.getMsg(
                        file?.getPath(),
                        headerOne.mp3StartByte.toHexString()
                    ))
                )
                return headerOne
            } else {
                log.warn(
                    (ErrorMessage.MP3_RECALCULATED_START_OF_MP3_AUDIO.getMsg(
                        file?.getPath(),
                        firstHeaderAfterTag.mp3StartByte.toHexString()
                    ))
                )
                return firstHeaderAfterTag
            }
        }
    }

    /**
     * @param startByte
     * @param endByte
     * @return
     * @return true if all the bytes between in the file between startByte and endByte are null, false
     * otherwise
     * @throws Exception
     */
    private fun isFilePortionNull(startByte: Int, endByte: Int): Boolean {
        log.debug(
            "Checking file portion:$startByte:${endByte.toHexString()}"
        )
        var fis: FileInputStream? = null
        var fc: FileChannel? = null
        try {
            fis = FileInputStream(file)
            fc = fis.getChannel()
            fc.position(startByte.toLong())
            val bb = ByteBuffer.allocateDirect(endByte - startByte)
            fc.read(bb)
            while (bb.hasRemaining()) {
                if (bb.get().toInt() != 0) {
                    return false
                }
            }
        } finally {
            if (fc != null) {
                fc.close()
            }

            if (fis != null) {
                fis.close()
            }
        }
        return true
    }

    /**
     * Sets the `Lyrics3` tag for this dataType. A new
     * `Lyrics3v2` dataType is created from the argument and then
     *
     * used here.
     *
     * @param mp3tag Any MP3Tag dataType can be used and will be converted into a
     * new Lyrics3v2 dataType.
     */
    /*
    void setLyrics3Tag(AbstractTag mp3tag)
    {
        lyrics3tag = new Lyrics3v2(mp3tag);
    }
    */
    /**
     *
     *
     * @param lyrics3tag
     */
    /*
    void setLyrics3Tag(AbstractLyrics3 lyrics3tag)
    {
        this.lyrics3tag = lyrics3tag;
    }
    */
    /**
     * Returns the `ID3v1` tag for this datatype.
     *
     * @return the `ID3v1` tag for this datatype
     */
    /*
    AbstractLyrics3 getLyrics3Tag()
    {
        return lyrics3tag;
    }
    */
    /**
     * @return a representation of tag as v24
     */
    fun getid3v2tagAsv24(): ID3v24Tag? {
        return id3v2Asv24tag
    }

    /**
     * Sets the v2 tag to the v2 tag provided as an argument.
     * Also store a v24 version of tag as v24 is the interface to be used
     * when talking with client applications.
     *
     * @param id3v2tag
     */
    fun setid3v2tag(id3v2tag: AbstractID3v2Tag?) {
        this.id3v2tag = id3v2tag
        if (id3v2tag is ID3v24Tag) {
            this.id3v2tagAsv24 = this.id3v2tag as ID3v24Tag
        } else {
            this.id3v2tagAsv24 = ID3v24Tag(id3v2tag)
        }
    }

    /**
     * Read lyrics3 Tag
     *
     *
     * TODO:not working
     *
     * @param file
     * @param newFile
     * @param loadOptions
     */
    private fun readLyrics3Tag(
        file: File?,
        newFile: RandomAccessFile?,
        loadOptions: Int
    ) {
        /*if ((loadOptions & LOAD_LYRICS3) != 0)
        {
            try
            {
                lyrics3tag = new Lyrics3v2(newFile);
            }
            catch (TagNotFoundException ex)
            {
            }
            try
            {
                if (lyrics3tag == null)
                {
                    lyrics3tag = new Lyrics3v1(newFile);
                }
            }
            catch (TagNotFoundException ex)
            {
            }
        }
        */
    }

    /**
     * Returns true if this datatype contains a `Lyrics3` tag
     * TODO disabled until Lyrics3 fixed
     * @return true if this datatype contains a `Lyrics3` tag
     */
    /*
    boolean hasLyrics3Tag()
    {
        return (lyrics3tag != null);
    }
    */
    /**
     * Extracts the raw ID3v2 tag data into a file.
     *
     *
     * This provides access to the raw data before manipulation, the data is written from the start of the file
     * to the start of the Audio Data. This is primarily useful for manipulating corrupted tags that are not
     * (fully) loaded using the standard methods.
     *
     * @param outputFile to write the data to
     * @return
     * @throws TagNotFoundException
     * @throws IOException
     */
    fun extractid3v2tagDataIntoFile(outputFile: File): File {
        val startByte = (audioHeader as MP3AudioHeader).mp3StartByte.toInt()
        if (startByte >= 0) {
            //Read byte into buffer
            val fis = FileInputStream(file)
            val fc = fis.getChannel()
            val bb = ByteBuffer.allocate(startByte)
            fc.read(bb)

            //Write bytes to outputFile
            val out = FileOutputStream(outputFile)
            out.write(bb.array())
            out.close()
            fc.close()
            fis.close()
            return outputFile
        }
        throw TagNotFoundException("There is no id3v2tag data in this file")
    }

    /**
     * Return audio header
     *
     * @return
     */
    fun getMP3AudioHeader(): MP3AudioHeader? {
        return audioHeader as? MP3AudioHeader
    }

    /**
     * Returns true if this datatype contains an `Id3v2` tag
     *
     * @return true if this datatype contains an `Id3v2` tag
     */
    fun hasid3v2tag(): Boolean {
        return (id3v2tag != null)
    }

    /**
     * Calculates hash with given algorithm. Buffer size is 32768 byte.
     * Hash is calculated EXCLUDING meta-data, like id3v1 or id3v2
     *
     * @param algorithm options MD5,SHA-1,SHA-256
     * @return hash value in byte
     * @throws IOException
     * @throws InvalidAudioFrameException
     * @throws NoSuchAlgorithmException
     */
    fun getHash(algorithm: String): ByteArray? {
        return getHash(algorithm, 32768)
    }

    /**
     * Calculates hash with algorithm "MD5", "SHA-1" or SHA-256".
     * Hash is calculated EXCLUDING meta-data, like id3v1 or id3v2
     *
     * @return byte[] hash value in byte
     * @throws IOException
     * @throws InvalidAudioFrameException
     * @throws NoSuchAlgorithmException
     */
    fun getHash(algorithm: String, bufferSize: Int): ByteArray? {
        val startByte = getMP3StartByte(file)

        var id3v1tagSize = 0
        if (hasid3v1tag()) {
            id3v1tagSize = id3v1tag?.size?:0
        }

        val inStream: InputStream = FileInputStream(file)

        val buffer = ByteArray(bufferSize)

        val digest = MessageDigest.getInstance(algorithm)

        inStream.skip(startByte)

        var read: Int
        val totalSize = (file?.length()?:0) - startByte - id3v1tagSize
        var pointer = buffer.size

        while (pointer <= totalSize) {
            read = inStream.read(buffer)

            digest.update(buffer, 0, read)
            pointer += buffer.size
        }
        read = inStream.read(buffer, 0, totalSize.toInt() - pointer + buffer.size)
        digest.update(buffer, 0, read)

        val hash = digest.digest()

        return hash
    }

    /**
     * Used by tags when writing to calculate the location of the music file
     *
     * @param file
     * @return the location within the file that the audio starts
     * @throws IOException
     * @throws InvalidAudioFrameException
     */
    fun getMP3StartByte(file: File?): Long {
        try {
            //Read ID3v2 tag size (if tag exists) to allow audio header parsing to skip over tag
            val startByte = AbstractID3v2Tag.getV2TagSizeIfExists(file)

            var audioHeader = MP3AudioHeader(file, startByte)
            if (startByte != audioHeader.mp3StartByte) {
                log.debug("First header found after tag:" + audioHeader)
                audioHeader = checkAudioStart(startByte, audioHeader)
            }
            return audioHeader.mp3StartByte
        } catch (iafe: InvalidAudioFrameException) {
            throw iafe
        } catch (ioe: IOException) {
            throw ioe
        }
    }

    /**
     * Returns true if this datatype contains an `Id3v1` tag
     *
     * @return true if this datatype contains an `Id3v1` tag
     */
    fun hasid3v1tag(): Boolean {
        return (id3v1tag != null)
    }

    fun setid3v1tag(id3v1tag: Tag?) {
        log.debug("setting tagv1:v1 tag")
        this.id3v1tag = id3v1tag as ID3v1Tag?
    }

    /**
     * Sets the `ID3v1` tag for this dataType. A new
     * `ID3v1_1` dataType is created from the argument and then used
     * here.
     *
     * @param mp3tag Any MP3Tag dataType can be used and will be converted into a
     * new ID3v1_1 dataType.
     */
    fun setid3v1tag(mp3tag: AbstractTag?) {
        log.debug("setting tagv1:abstract")
        id3v1tag = ID3v11Tag(mp3tag)
    }

    /**
     * Calculates hash with given buffer size.
     * Hash is calculated EXCLUDING meta-data, like id3v1 or id3v2
     *
     * @param buffer
     * @return byte[] hash value in byte
     * @throws IOException
     * @throws InvalidAudioFrameException
     * @throws NoSuchAlgorithmException
     */
    fun getHash(buffer: Int): ByteArray? {
        return getHash("MD5", buffer)
    }

    val hash: ByteArray?
        /**
         * Calculates hash with algorithm "MD5". Buffer size is 32768 byte.
         * Hash is calculated EXCLUDING meta-data, like id3v1 or id3v2
         *
         * @return byte[] hash value.
         * @throws IOException
         * @throws InvalidAudioFrameException
         * @throws NoSuchAlgorithmException
         */
        get() = getHash("MD5", 32768)

    /**
     * Set v2 tag ,don't need to set v24 tag because saving
     *
     * @param id3v2tag
     */
    //TODO temp its rather messy
    fun setid3v2tagOnly(id3v2tag: AbstractID3v2Tag?) {
        this.id3v2tag = id3v2tag
        this.id3v2tagAsv24 = null
    }

//    /**
//     * Remove tag from file
//     *
//     * @param mp3tag
//     * @throws FileNotFoundException
//     * @throws IOException
//     */
//    fun delete(mp3tag: AbstractTag) {
//        val raf = RandomAccessFile(this.file, "rw")
//        mp3tag.delete(raf)
//        raf.close()
//        if (mp3tag is id3v1tag) {
//            id3v1tag = null
//        }
//
//        if (mp3tag is Abstractid3v2tag) {
//            id3v2tag = null
//        }
//    }
//
//    /**
//     * Overridden for compatibility with merged code
//     *
//     * @throws NoWritePermissionsException if the file could not be written to due to file permissions
//     * @throws CannotWriteException
//     */
//    override fun commit() {
//        try {
//            save()
//        } catch (umfe: UnableToModifyFileException) {
//            throw NoWritePermissionsException(umfe)
//        } catch (ioe: IOException) {
//            throw CannotWriteException(ioe)
//        } catch (te: TagException) {
//            throw CannotWriteException(te)
//        }
//    }

    /**
     * Saves the tags in this dataType to the file argument. It will be saved as
     * TagConstants.MP3_FILE_SAVE_WRITE
     *
     * @param fileToSave file to save the this dataTypes tags to
     * @throws FileNotFoundException if unable to find file
     * @throws IOException           on any I/O error
     */
    /**
     * Saves the tags in this dataType to the file referred to by this dataType.
     *
     * @throws IOException  on any I/O error
     * @throws TagException on any exception generated by this library.
     */
    fun save(fileToSave: File? = this.file) {
        if (fileToSave == null) {
            return
        }
        //Ensure we are dealing with absolute filepaths not relative ones
        val file = fileToSave.getAbsoluteFile()

        log.debug("Saving  : " + file.getPath())

        //Checks before starting write
        precheck(file)

        var rfile: RandomAccessFile? = null
        try {
            //ID3v2 Tag
            if (TagOptionSingleton.id3v2Save) {
                if (id3v2tag == null) {
                    rfile = RandomAccessFile(file, "rw")
                    (ID3v24Tag()).delete(rfile)
                    (ID3v23Tag()).delete(rfile)
                    (ID3v22Tag()).delete(rfile)
                    log.debug("Deleting ID3v2 tag:" + file.getName())
                    rfile.close()
                } else {
                    log.debug("Writing ID3v2 tag:" + file.getName())
                    val mp3AudioHeader =
                        this.audioHeader as? MP3AudioHeader
                    val mp3StartByte = mp3AudioHeader?.mp3StartByte?:0
                    val newMp3StartByte = id3v2tag?.write(file, mp3StartByte?:0)
                    if (mp3StartByte != newMp3StartByte) {
                        log.debug("New mp3 start byte: $newMp3StartByte")
                        mp3AudioHeader?.mp3StartByte = newMp3StartByte?:0
                    }
                }
            }
            rfile = RandomAccessFile(file, "rw")

            //Lyrics 3 Tag
            if (TagOptionSingleton.lyrics3Save) {
                if (lyrics3tag != null) {
                    lyrics3tag.write(rfile)
                }
            }
            //ID3v1 tag
            if (TagOptionSingleton.id3v1Save) {
                log.debug("Processing ID3v1")
                if (id3v1tag == null) {
                    log.debug("Deleting ID3v1")
                    (ID3v1Tag()).delete(rfile)
                } else {
                    log.debug("Saving ID3v1")
                    id3v1tag?.write(rfile)
                }
            }
        } catch (ex: FileNotFoundException) {
            log.error(
                ErrorMessage.GENERAL_WRITE_FAILED_BECAUSE_FILE_NOT_FOUND.getMsg(
                    file.getName()
                ),
                ex
            )
            throw ex
        } catch (iex: IOException) {
            log.error(
                ErrorMessage.GENERAL_WRITE_FAILED_BECAUSE.getMsg(
                    file.getName(),
                    iex.message
                ),
                iex
            )
            throw iex
        } catch (re: RuntimeException) {
            log.error(
                ErrorMessage.GENERAL_WRITE_FAILED_BECAUSE.getMsg(
                    file.getName(),
                    re.message
                ),
                re
            )
            throw re
        } finally {
            if (rfile != null) {
                rfile.close()
            }
        }
    }

    /**
     * Check can write to file
     *
     * @param file
     * @throws IOException
     */
    fun precheck(file: File) {
        if (!file.exists()) {
            log.error(
                ErrorMessage.GENERAL_WRITE_FAILED_BECAUSE_FILE_NOT_FOUND.getMsg(
                    file.getName()
                )
            )
            throw IOException(
                ErrorMessage.GENERAL_WRITE_FAILED_BECAUSE_FILE_NOT_FOUND.getMsg(
                    file.getName()
                )
            )
        }

        if (TagOptionSingleton.checkIsWritable && !file.canWrite()
        ) {
            log.error(ErrorMessage.GENERAL_WRITE_FAILED.getMsg(file.getName()))
            throw IOException(
                ErrorMessage.GENERAL_WRITE_FAILED.getMsg(file.getName())
            )
        }

        if (file.length() <= MINIMUM_FILESIZE) {
            log.error(
                ErrorMessage.GENERAL_WRITE_FAILED_BECAUSE_FILE_IS_TOO_SMALL.getMsg(
                    file.getName()
                )
            )
            throw IOException(
                ErrorMessage.GENERAL_WRITE_FAILED_BECAUSE_FILE_IS_TOO_SMALL.getMsg(
                    file.getName()
                )
            )
        }
    }

    /**
     * Displays MP3File Structure
     */
    override fun displayStructureAsXML(): String? {
        createXMLStructureFormatter()
        tagFormatter?.openHeadingElement("file", this.file?.getAbsolutePath()?:"")
        if (this.id3v1tag != null) {
            this.id3v1tag?.createStructure()
        }
        if (this.id3v2tag != null) {
            this.id3v2tag?.createStructure()
        }
        tagFormatter?.closeHeadingElement("file")
        return tagFormatter.toString()
    }

    /**
     * Displays MP3File Structure
     */
    override fun displayStructureAsPlainText(): String? {
        createPlainTextStructureFormatter()
        tagFormatter?.openHeadingElement("file", this.file?.getAbsolutePath()?:"")
        if (this.id3v1tag != null) {
            this.id3v1tag?.createStructure()
        }
        if (this.id3v2tag != null) {
            this.id3v2tag?.createStructure()
        }
        tagFormatter?.closeHeadingElement("file")
        return tagFormatter.toString()
    }

    /**
     * Get the ID3v2 tag and convert to preferred version or if the file doesn't have one at all
     * create a default tag of preferred version and set it. The file may already contain a ID3v1 tag but because
     * this is not terribly useful the v1tag is not considered for this problem.
     *
     * @return
     */
    override fun getTagAndConvertOrCreateAndSetDefault(): Tag {
        setTag(
            convertID3Tag(
                getTagOrCreateDefault() as AbstractID3v2Tag?,
                TagOptionSingleton.id3v2Version
            )
        )
        return getTag()!!
    }

    /**
     * Set the Tag
     *
     *
     * If the parameter tag is a v1tag then the v1 tag is set if v2tag then the v2tag.
     *
     * @param tag
     */
    override fun setTag(tag: Tag?) {
        super.setTag(tag)
        if (tag is ID3v1Tag) {
            this.id3v1tag = tag
        } else {
            setid3v2tag(tag as AbstractID3v2Tag?)
        }
    }

    /**
     * Overridden to only consider ID3v2 Tag
     *
     * @return
     */
    override fun getTagOrCreateDefault(): Tag? {
        return id3v2tag ?: return createDefaultTag()
    }

    /**
     * Create Default Tag
     *
     * @return
     */
    override fun createDefaultTag(): Tag? {
        return TagOptionSingleton.createDefaultID3Tag()
    }
}
