package de.visualdigits.kaudiotagger.model.id3.types

enum class Languages(
    val description: String
) {

        aar("Afar"),
        abk("Abkhazian"),
        ace("Achinese"),
        ach("Acoli"),
        ada("Adangme"),
        afa("Afro-Asiatic"),
        afh("Afrihili"),
        afr("Afrikaans"),
        aka("Akan"),
        akk("Akkadian"),
        alb("Albanian"),
        ale("Aleut"),
        alg("Algonquian languages"),
        amh("Amharic"),
        ang("Old English,(ca.450-1100)"),
        apa("Apache languages"),
        ara("Arabic"),
        arc("Aramaic"),
        arm("Armenian"),
        arn("Araucanian"),
        arp("Arapaho"),
        art("Artificial"),
        arw("Arawak"),
        asm("Assamese"),
        ast("Asturian; Bable"),
        ath("Athapascan languages"),
        aus("Australian languages"),
        ava("Avaric"),
        ave("Avestan"),
        awa("Awadhi"),
        aym("Aymara"),
        aze("Azerbaijani"),
        bad("Banda"),
        bai("Bamileke languages"),
        bak("Bashkir"),
        bal("Baluchi"),
        bam("Bambara"),
        ban("Balinese"),
        baq("Basque"),
        bas("Basa"),
        bat("Baltic"),
        bej("Beja"),
        bel("Belarusian"),
        bem("Bemba"),
        ben("Bengali"),
        ber("Berber"),
        bho("Bhojpuri"),
        bih("Bihari"),
        bik("Bikol"),
        bin("Bini"),
        bis("Bislama"),
        bla("Siksika"),
        bnt("Bantu"),
        bod("Tibetan"),
        bos("Bosnian"),
        bra("Braj"),
        bre("Breton"),
        btk("Batak (Indonesia)"),
        bua("Buriat"),
        bug("Buginese"),
        bul("Bulgarian"),
        bur("Burmese"),
        cad("Caddo"),
        cai("Central American Indian"),
        car("Carib"),
        cat("Catalan"),
        cau("Caucasian"),
        ceb("Cebuano"),
        cel("Celtic"),
        ces("Czech"),
        cha("Chamorro"),
        chb("Chibcha"),
        che("Chechen"),
        chg("Chagatai"),
        chi("Chinese"),
        chk("Chuukese"),
        chm("Mari"),
        chn("Chinook jargon"),
        cho("Choctaw"),
        chp("Chipewyan"),
        chr("Cherokee"),
        chu("Church Slavic"),
        chv("Chuvash"),
        chy("Cheyenne"),
        cmc("Chamic languages"),
        cop("Coptic"),
        cor("Cornish"),
        cos("Corsican"),
        cpe("Creoles and pidgins, English based"),
        cpf("Creoles and pidgins, French based"),
        cpp("Creoles and pidgins"),
        cre("Cree"),
        crp("Creoles and pidgins"),
        cus("Cushitic"),
        cym("Welsh"),
        cze("Czech"),
        dak("Dakota"),
        dan("Danish"),
        day("Dayak"),
        del("Delaware"),
        den("Slave (Athapascan)"),
        deu("German"),
        dgr("Dogrib"),
        din("Dinka"),
        div("Divehi"),
        doi("Dogri"),
        dra("Dravidian"),
        dua("Duala"),
        dum("Dutch, Middle (ca.1050-1350)"),
        dut("Dutch"),
        dyu("Dyula"),
        dzo("Dzongkha"),
        efi("Efik"),
        egy("Egyptian (Ancient)"),
        eka("Ekajuk"),
        ell("Greek, Modern (1453-)"),
        elx("Elamite"),
        eng("English"),
        enm("English, Middle (1100-1500)"),
        epo("Esperanto"),
        est("Estonian"),
        eus("Basque"),
        ewe("Ewe"),
        ewo("Ewondo"),
        fan("Fang"),
        fao("Faroese"),
        fas("Persian"),
        fat("Fanti"),
        fij("Fijian"),
        fin("Finnish"),
        fiu("Finno-Ugrian"),
        fon("Fon"),
        fra("French"),
        frm("French, Middle (ca.1400-1800)"),
        fro("French, Old (842-ca.1400)"),
        fry("Frisian"),
        ful("Fulah"),
        fur("Friulian"),
        gaa("Ga"),
        gay("Gayo"),
        gba("Gbaya"),
        gem("Germanic"),
        geo("Georgian"),
        ger("German"),
        gez("Geez"),
        gil("Gilbertese"),
        gla("Gaelic; Scottish Gaelic"),
        gle("Irish"),
        glg("Gallegan"),
        glv("Manx"),
        gmh("German, Middle High (ca.1050-1500)"),
        goh("German, Old High (ca.750-1050)"),
        gon("Gondi"),
        gor("Gorontalo"),
        got("Gothic"),
        grb("Grebo"),
        grc("Greek, Ancient (to 1453)"),
        gre("Greek, Modern (1453-)"),
        grn("Guarani"),
        guj("Gujarati"),
        gwi("Gwich´in"),
        hai("Haida"),
        hau("Hausa"),
        haw("Hawaiian"),
        heb("Hebrew"),
        her("Herero"),
        hil("Hiligaynon"),
        him("Himachali"),
        hin("Hindi"),
        hit("Hittite"),
        hmn("Hmong"),
        hmo("Hiri Motu"),
        hrv("Croatian"),
        hun("Hungarian"),
        hup("Hupa"),
        hye("Armenian"),
        iba("Iban"),
        ibo("Igbo"),
        ice("Icelandic"),
        ido("Ido"),
        ijo("Ijo"),
        iku("Inuktitut"),
        ile("Interlingue"),
        ilo("Iloko"),
        ina("Interlingua"),
        inc("Indic"),
        ind("Indonesian"),
        ine("Indo-European"),
        ipk("Inupiaq"),
        ira("Iranian (Other)"),
        iro("Iroquoian languages"),
        isl("Icelandic"),
        ita("Italian"),
        jav("Javanese"),
        jpn("Japanese"),
        jpr("Judeo-Persian"),
        jrb("Judeo-Arabic"),
        kaa("Kara-Kalpak"),
        kab("Kabyle"),
        kac("Kachin"),
        kal("Kalaallisut"),
        kam("Kamba"),
        kan("Kannada"),
        kar("Karen"),
        kas("Kashmiri"),
        kat("Georgian"),
        kau("Kanuri"),
        kaw("Kawi"),
        kaz("Kazakh"),
        kha("Khasi"),
        khi("Khoisan"),
        khm("Khmer"),
        kho("Khotanese"),
        kik("Kikuyu; Gikuyu"),
        kin("Kinyarwanda"),
        kir("Kirghiz"),
        kmb("Kimbundu"),
        kok("Konkani"),
        kom("Komi"),
        kon("Kongo"),
        kor("Korean"),
        kos("Kosraean"),
        kpe("Kpelle"),
        kro("Kru"),
        kru("Kurukh"),
        kua("Kuanyama; Kwanyama"),
        kum("Kumyk"),
        kur("Kurdish"),
        kut("Kutenai"),
        lad("Ladino"),
        lah("Lahnda"),
        lam("Lamba"),
        lao("Lao"),
        lat("Latin"),
        lav("Latvian"),
        lez("Lezghian"),
        lin("Lingala"),
        lit("Lithuanian"),
        lol("Mongo"),
        loz("Lozi"),
        ltz("Luxembourgish; Letzeburgesch"),
        lua("Luba-Lulua"),
        lub("Luba-Katanga"),
        lug("Ganda"),
        lui("Luiseno"),
        lun("Lunda"),
        luo("Luo (Kenya and Tanzania)"),
        lus("lushai"),
        mac("Macedonian"),
        mad("Madurese"),
        mag("Magahi"),
        mah("Marshallese"),
        mai("Maithili"),
        mak("Makasar"),
        mal("Malayalam"),
        man("Mandingo"),
        mao("Maori"),
        map("Austronesian"),
        mar("Marathi"),
        mas("Masai"),
        may("Malay"),
        mdr("Mandar"),
        men("Mende"),
        mga("Irish, Middle (900-1200)"),
        mic("Micmac"),
        min("Minangkabau"),
        mis("Miscellaneous languages"),
        mkd("Macedonian"),
        mkh("Mon-Khmer"),
        mlg("Malagasy"),
        mlt("Maltese"),
        mnc("Manchu"),
        mni("Manipuri"),
        mno("Manobo languages"),
        moh("Mohawk"),
        mol("Moldavian"),
        mon("Mongolian"),
        mos("Mossi"),
        mri("Maori"),
        msa("Malay"),
        mul("Multiple languages"),
        mun("Munda languages"),
        mus("Creek"),
        mwr("Marwari"),
        mya("Burmese"),
        myn("Mayan languages"),
        nah("Nahuatl"),
        nai("North American Indian"),
        nau("Nauru"),
        nav("Navajo; Navaho"),
        nbl("South Ndebele"),
        nde("North Ndebele"),
        ndo("Ndonga"),
        nds("Low German; Low Saxon"),
        nep("Nepali"),
        new("Newari"),
        nia("Nias"),
        nic("Niger-Kordofanian"),
        niu("Niuean"),
        nld("Dutch"),
        nno("Norwegian Nynorsk"),
        nob("Norwegian Bokmål"),
        non("Norse, Old"),
        nor("Norwegian"),
        nso("Sotho, Northern"),
        nub("Nubian languages"),
        nya("Chichewa; Chewa; Nyanja"),
        nym("Nyamwezi"),
        nyn("Nyankole"),
        nyo("Nyoro"),
        nzi("Nzima"),
        oci("Occitan (post 1500); Provençal"),
        oji("Ojibwa"),
        ori("Oriya"),
        orm("Oromo"),
        osa("Osage"),
        oss("Ossetian; Ossetic"),
        ota("Turkish, Ottoman (1500-1928)"),
        oto("Otomian languages"),
        paa("Papuan"),
        pag("Pangasinan"),
        pal("Pahlavi"),
        pam("Pampanga"),
        pan("Panjabi"),
        pap("Papiamento"),
        pau("Palauan"),
        peo("Persian, Old (ca.600-400 B.C.)"),
        per("Persian"),
        phi("Philippine"),
        phn("Phoenician"),
        pli("Pali"),
        pol("Polish"),
        pon("Pohnpeian"),
        por("Portuguese"),
        pra("Prakrit languages"),
        pro("Provençal, Old (to 1500)"),
        pus("Pushto"),
        que("Quechua"),
        raj("Rajasthani"),
        rap("Rapanui"),
        rar("Rarotongan"),
        roa("Romance"),
        roh("Raeto-Romance"),
        rom("Romany"),
        ron("Romanian"),
        rum("Romanian"),
        run("Rundi"),
        rus("Russian"),
        sad("Sandawe"),
        sag("Sango"),
        sah("Yakut"),
        sai("South American Indian"),
        sal("Salishan languages"),
        sam("Samaritan Aramaic"),
        san("Sanskrit"),
        sas("Sasak"),
        sat("Santali"),
        scc("Serbian"),
        sco("Scots"),
        scr("Croatian"),
        sel("Selkup"),
        sem("Semitic"),
        sga("Irish, Old (to 900)"),
        sgn("Sign languages"),
        shn("Shan"),
        sid("Sidamo"),
        sin("Sinhales"),
        sio("Siouan languages"),
        sit("Sino-Tibetan"),
        sla("Slavic"),
        slk("Slovak"),
        slo("Slovak"),
        slv("Slovenian"),
        sma("Southern Sami"),
        sme("Northern Sami"),
        smi("Sami languages"),
        smj("Lule Sami"),
        smn("Inari Sami"),
        smo("Samoan"),
        sms("Skolt Sami"),
        sna("Shona"),
        snd("Sindhi"),
        snk("Soninke"),
        sog("Sogdian"),
        som("Somali"),
        son("Songhai"),
        sot("Sotho, Southern"),
        spa("Spanish; Castilia"),
        sqi("Albanian"),
        srd("Sardinian"),
        srp("Serbian"),
        srr("Serer"),
        ssa("Nilo-Saharan"),
        sus("Susu"),
        sux("Sumerian"),
        swa("Swahili"),
        swe("Swedish"),
        syr("Syriac"),
        tah("Tahitian"),
        tai("Tai"),
        tam("Tamil"),
        tat("Tatar"),
        tel("Telugu"),
        tem("Timne"),
        ter("Tereno"),
        tet("Tetum"),
        tgk("Tajik"),
        tgl("Tagalog"),
        tha("Thai"),
        tib("Tibetan"),
        tig("Tigre"),
        tir("Tigrinya"),
        tiv("Tiv"),
        tkl("Tokelau"),
        tli("Tlingit"),
        tmh("Tamashek"),
        tog("Tonga (Nyasa)"),
        ton("Tonga (Tonga Islands)"),
        tpi("Tok Pisin"),
        tsi("Tsimshian"),
        tsn("Tswana"),
        tso("Tsonga"),
        tuk("Turkmen"),
        tum("Tumbuka"),
        tup("Tupi"),
        tur("Turkish"),
        tut("Altaic"),
        tvl("Tuvalu"),
        twi("Twi"),
        tyv("Tuvinian"),
        uga("Ugaritic"),
        uig("Uighur"),
        ukr("Ukrainian"),
        umb("Umbundu"),
        und("Undetermined"),
        urd("Urdu"),
        uzb("Uzbek"),
        vai("Vai"),
        ven("Venda"),
        vie("Vietnamese"),
        vol("Volapük"),
        vot("Votic"),
        wak("Wakashan languages"),
        wal("Walamo"),
        war("Waray"),
        was("Washo"),
        wel("Welsh"),
        wen("Sorbian languages"),
        wln("Walloon"),
        wol("Wolof"),
        xho("Xhosa"),
        yao("Yao"),
        yap("Yapese"),
        yid("Yiddish"),
        yor("Yoruba"),
        ypk("Yupik languages"),
        zap("Zapotec"),
        zen("Zenaga"),
        zha("Zhuang; Chuang"),
        zho("Chinese"),
        znd("Zande"),
        zul("Zulu"),
        zun("Zuni"),
        winamp("Winamp Format"), // Not Part of Spec but commonly used by some applications
        mediamonkey("Media Monkey Format"), // Not Part of Spec but commonly used by some applications
    ;

    companion object {

        const val DEFAULT_ID: String = "eng"
        const val MEDIA_MONKEY_ID: String = "XXX"
        const val WINAMP_ID: String = "\u0000\u0000\u0000"

        const val DEFAULT_VALUE: String = "English"

        // The number of bytes used to hold the language field size
        const val LANGUAGE_FIELD_SIZE: Int = 3

        fun fromDescription(description: String?): Languages? = entries.find { e -> e.description == description }

        fun getValueToIdMap(): Map<String, String> = entries.associate { e -> Pair(e.description, e.name) }

        fun getIdToValueMap(): Map<String, String> = entries.associate { e -> Pair(e.name, e.description) }
    }
}