package de.visualdigits.kaudiotagger.model.id3.types

object MusicianCredits {

    val musicianCredits = mutableSetOf(
        "12 string guitar",
        "17-string koto",
        "accompaniment",
        "accordina",
        "accordion",
        "acoustic",
        "additional",
        "aeolian harp",
        "afoxé",
        "afuche / cabasa",
        "agogô",
        "ajaeng",
        "akete",
        "alfaia",
        "algozey",
        "alphorn",
        "alto",
        "amadinda",
        "ankle rattlers",
        "anvil",
        "appalachian dulcimer",
        "archlute",
        "archtop guitar",
        "arghul",
        "assistant",
        "associate",
        "atabaque",
        "atarigane",
        "autoharp",
        "background vocals",
        "baglama",
        "bagpipe",
        "band",
        "bajo sexto",
        "balafon",
        "balalaika",
        "baltic psalteries",
        "bamboo angklung",
        "bandoneón",
        "bandora",
        "bandura",
        "bandurria",
        "bangu",
        "banhu",
        "banjitar",
        "banjo",
        "bansuri",
        "baritone",
        "baroque",
        "barrel drum",
        "barrel organ",
        "baryton",
        "bass",
        "batá drum",
        "bawu",
        "bayan",
        "bazooka",
        "bellow-blown bagpipes",
        "bells",
        "bell tree",
        "bendir",
        "berimbau",
        "bicycle bell",
        "bin-sasara",
        "birch lur",
        "biwa",
        "boatswain's pipe",
        "bodhrán",
        "body percussion",
        "bolon",
        "bombarde",
        "bones",
        "bongos",
        "bouzouki",
        "bowed piano",
        "bowed psaltery",
        "bowed string instruments",
        "brass",
        "bronze lur",
        "brushes",
        "bugle",
        "buisine",
        "buk",
        "bulbul tarang",
        "bullroarer",
        "button accordion",
        "buzuq",
        "cajón",
        "calabash",
        "calliope",
        "cancelled",
        "carillon",
        "castanets",
        "cavaquinho",
        "caxixi",
        "celeste",
        "celesta",
        "cello",
        "cembalet",
        "çevgen",
        "chacha",
        "chainsaw",
        "chakhe",
        "chalumeau",
        "chamberlin",
        "chamber",
        "chande",
        "chanzy",
        "chap",
        "chapman stick",
        "charango",
        "chau gong",
        "chikuzen biwa",
        "chime bar",
        "chimes",
        "ching",
        "chitra veena",
        "choir",
        "chromatic button accordion",
        "chromatic harmonica",
        "citole",
        "cittern",
        "cizhonghu",
        "clarinet",
        "classical guitar",
        "classical kemençe",
        "claves",
        "clavichord",
        "clavinet",
        "claviola",
        "co",
        "cò ke",
        "concert flute",
        "concert harp",
        "concertina",
        "conch",
        "congas",
        "continuum",
        "contrabass clarinet",
        "contrabassoon",
        "contrabass recorder",
        "contrabass saxophone",
        "contralto vocals",
        "cornamuse",
        "cornet",
        "cornett",
        "countertenor vocals",
        "cover",
        "cowbell",
        "craviola",
        "cretan lyra",
        "cristal baschet",
        "crotales",
        "crumhorn",
        "crwth",
        "cuatro",
        "cuíca",
        "cümbüş",
        "cylindrical drum",
        "cymbals",
        "cymbalum",
        "daegeum",
        "daf",
        "daire",
        "daluo",
        "đàn bầu",
        "đàn nguyệt",
        "đàn nhị",
        "đàn tam",
        "đàn tam thập lục",
        "đàn tranh",
        "đàn tứ",
        "đàn tứ dây",
        "đàn tỳ bà",
        "darbuka",
        "daruan",
        "davul",
        "denis d'or",
        "descant recorder / soprano recorder",
        "dhol",
        "dholak",
        "diatonic accordion / melodeon",
        "diddley bow",
        "didgeridoo",
        "dilruba",
        "đing buốt",
        "đing năm",
        "ding tac ta",
        "disk drive",
        "diyingehu",
        "dizi",
        "djembe",
        "dobro",
        "dohol",
        "dolceola",
        "dombra",
        "domra",
        "donso ngɔni",
        "doshpuluur",
        "double bass",
        "double reed",
        "doyra",
        "dramyin",
        "drum machine",
        "drums",
        "drumset",
        "dubreq stylophone",
        "duck call",
        "duct flute",
        "duduk",
        "dulce melos",
        "dulcian",
        "dulzaina",
        "dunun",
        "dutar",
        "duxianqin",
        "ebow",
        "effects",
        "e-flat clarinet",
        "ektara",
        "electric bass guitar",
        "electric cello",
        "electric fretless guitar",
        "electric grand piano",
        "electric guitar",
        "electric harp",
        "electric lap steel guitar",
        "electric piano",
        "electric sitar",
        "electric upright bass",
        "electric viola",
        "electric violin",
        "electronic drum set",
        "electronic instruments",
        "electronic organ",
        "electronic wind instrument",
        "emeritus",
        "end-blown flute",
        "english horn",
        "erhu",
        "esraj",
        "euphonium",
        "ewi",
        "executive",
        "farfisa",
        "fiddle",
        "fife",
        "finger cymbals",
        "finger snaps",
        "five-string banjo",
        "floppy disk drive",
        "flugelhorn",
        "flumpet",
        "flute",
        "flûte d'amour",
        "folk harp",
        "foot percussion",
        "fortepiano",
        "four-string banjo",
        "fourth flute",
        "frame drum",
        "free reed",
        "french horn",
        "fretless bass",
        "friction drum",
        "friction idiophone",
        "frottoir",
        "fujara",
        "gadulka",
        "gamelan",
        "gankogui",
        "ganzá",
        "gaohu",
        "garifuna drum",
        "garklein recorder",
        "gayageum",
        "gehu",
        "geomungo",
        "german harp",
        "ghatam",
        "ģīga",
        "gittern",
        "gizmo",
        "glass harmonica",
        "glass harp",
        "glockenspiel",
        "goblet drum",
        "gong",
        "gong bass drum",
        "gongs",
        "gralla",
        "gramorimba",
        "grand piano",
        "great bass recorder / c-bass recorder",
        "greek baglama",
        "guan",
        "gudok",
        "guest",
        "güiro",
        "guitalele",
        "guitar",
        "guitaret",
        "guitaret",
        "guitarrón chileno",
        "guitarrón mexicano",
        "guitars",
        "guitar synthesizer",
        "gumbri",
        "guqin",
        "gusli",
        "gut guitar",
        "guzheng",
        "haegeum",
        "hammered dulcimer",
        "hammond organ",
        "handbells",
        "handclaps",
        "hang",
        "hardart",
        "hard disk drive",
        "hardingfele",
        "harmonica",
        "harmonium",
        "harp",
        "harp guitar",
        "harpsichord",
        "hawaiian guitar",
        "heckelphone",
        "heike biwa",
        "helicon",
        "hichiriki",
        "hi-hat",
        "hmông flute",
        "horn",
        "hotchiku",
        "hourglass drum",
        "hulusi",
        "huqin",
        "hurdy gurdy",
        "idiophone",
        "igil",
        "indian bamboo flutes",
        "instrument",
        "instrumental",
        "irish bouzouki",
        "irish harp / clàrsach",
        "janggu",
        "jew's harp",
        "jing",
        "jing'erhu",
        "jinghu",
        "jouhikko",
        "jug",
        "kamancheh",
        "kanjira",
        "kanklės",
        "kantele",
        "kanun",
        "kartal",
        "kaval",
        "kazoo",
        "kemençe of the black sea",
        "kemenche",
        "kèn bầu",
        "kèn lá",
        "keyboard",
        "keyboard bass",
        "keyed brass instruments",
        "keytar",
        "khene",
        "khèn mèo",
        "khim",
        "khlui",
        "khong wong",
        "khong wong lek",
        "khong wong yai",
        "kinnor",
        "ki pah",
        "kithara",
        "kkwaenggwari",
        "klong khaek",
        "k'lông pút",
        "klong song na",
        "klong that",
        "klong yao",
        "kōauau",
        "kokyu",
        "komuz",
        "kora",
        "kortholt",
        "kös",
        "koto",
        "kotsuzumi",
        "krakebs",
        "krar",
        "kudüm",
        "lamellophone",
        "langeleik",
        "laouto",
        "lap steel guitar",
        "laser harp",
        "lasso d'amore",
        "launeddas",
        "lautenwerck",
        "lavta",
        "lead vocals",
        "limbe",
        "lirone",
        "lithophone",
        "liuqin",
        "live",
        "low whistle",
        "lute",
        "luthéal",
        "lyre",
        "lyricon",
        "madal",
        "maddale",
        "mandocello",
        "mandola",
        "mandolin",
        "mandolute",
        "maracas",
        "marimba",
        "marimba lumina",
        "marímbula",
        "mark tree",
        "marxophone",
        "mbira",
        "medium",
        "medium 1",
        "medium 2",
        "medium 3",
        "medium 4",
        "medium 5",
        "medium 6",
        "medium 7",
        "medium 8",
        "medium 9",
        "medley",
        "mellophone",
        "mellotron",
        "melodica",
        "mendoza",
        "metal angklung",
        "metallophone",
        "mexican vihuela",
        "mezzo-soprano vocals",
        "minimoog",
        "minipiano",
        "minor",
        "mirliton",
        "moog",
        "morin khuur / matouqin",
        "morsing",
        "mouth organ",
        "mridangam",
        "mukkuri",
        "musette de cour",
        "musical bow",
        "musical box",
        "musical saw",
        "nabal",
        "nadaswaram",
        "nagadou-daiko",
        "nagak",
        "nai",
        "não bạt / chập chõa",
        "naobo",
        "natural brass instruments",
        "natural horn",
        "ney",
        "ngɔni",
        "nguru",
        "nohkan",
        "northumbrian pipes",
        "nose flute",
        "nose whistle",
        "number",
        "nyatiti",
        "nyckelharpa",
        "nylon guitar",
        "oboe",
        "oboe da caccia",
        "oboe d'amore",
        "ocarina",
        "ocean drum",
        "octave mandolin",
        "oktawka",
        "omnichord",
        "ondes martenot",
        "ophicleide",
        "organ",
        "original",
        "orpharion",
        "other instruments",
        "other vocals",
        "ōtsuzumi",
        "oud",
        "pahū pounamu",
        "pakhavaj",
        "pan flute",
        "pang gu ly hu hmông",
        "paraguayan harp",
        "parody",
        "partial",
        "pātē",
        "pedal piano",
        "pedal steel guitar",
        "percussion",
        "phách",
        "pi",
        "pianet",
        "piano",
        "piccolo",
        "pi nai",
        "pipa",
        "pipe organ",
        "piri",
        "pí thiu",
        "pkhachich",
        "plucked string instruments",
        "pocket trumpet",
        "poi awhiowhio",
        "portuguese guitar",
        "pōrutu",
        "post horn",
        "practice chanter",
        "prepared piano",
        "primero",
        "principal",
        "psaltery",
        "pūkaea",
        "pūmotomoto",
        "pūrerehua",
        "pūtātara",
        "pūtōrino",
        "qilaut",
        "quena",
        "quijada",
        "quinto",
        "rainstick",
        "rammana",
        "ranat ek",
        "ranat kaeo",
        "ranat thum",
        "ratchet",
        "rattle",
        "rauschpfeife",
        "ravanahatha",
        "reactable",
        "rebab",
        "rebec",
        "recorder",
        "reco-reco",
        "reed organ",
        "reeds",
        "rehu",
        "repinique",
        "resonator guitar",
        "rhodes piano",
        "rhythm sticks",
        "riq",
        "rondador",
        "rototom",
        "ruan",
        "rudra veena",
        "ryuteki",
        "sabar",
        "sackbut",
        "samba whistle",
        "sampler",
        "sanshin",
        "santoor",
        "santur",
        "sanxian",
        "sáo meò",
        "saó ôi flute",
        "sáo trúc",
        "sapek clappers",
        "sarangi",
        "saraswati veena",
        "šargija",
        "sarod",
        "saron",
        "sarrusophone",
        "satsuma biwa",
        "saw duang",
        "saw sam sai",
        "saw u",
        "sax",
        "saxophone",
        "saz",
        "schwyzerörgeli",
        "scottish smallpipes",
        "segunda",
        "sênh tiền",
        "serpent",
        "setar",
        "shakers",
        "shakuhachi",
        "shamisen",
        "shawm",
        "shehnai",
        "shekere",
        "sheng",
        "shichepshin",
        "shime-daiko",
        "shinobue",
        "sho",
        "shofar",
        "shruti box",
        "shudraga",
        "siku",
        "singing bowl",
        "single reed",
        "sistrum",
        "sitar",
        "slide",
        "slit drum",
        "snare drum",
        "solo",
        "song loan",
        "sopilka",
        "sopranino",
        "soprano",
        "sousaphone",
        "spanish",
        "spilåpipa",
        "spinet",
        "spinettone",
        "spoken vocals",
        "spoons",
        "steel guitar",
        "steelpan",
        "steel-string guitar",
        "strings",
        "string quartet",
        "string ensemble",
        "stroh violin",
        "struck idiophone",
        "struck string instruments",
        "subcontrabass recorder",
        "suikinkutsu",
        "suka",
        "suling",
        "suona",
        "surdo",
        "swarmandal",
        "swedish bagpipes",
        "synclavier",
        "synthesizer",
        "syrinx",
        "tabla",
        "table steel guitar",
        "tack piano",
        "taepyeongso",
        "taiko",
        "taishogoto",
        "talharpa",
        "talkbox",
        "talking drum",
        "tamborim",
        "tambourine",
        "tambura",
        "tamburitza",
        "tanbou ka",
        "tanbur",
        "tangent piano",
        "taonga pūoro",
        "tap dancing",
        "tape",
        "taphon",
        "tar",
        "taragot",
        "tef",
        "teleharmonium",
        "temple blocks",
        "tenor",
        "thavil",
        "theatre organ",
        "theorbo",
        "theremin",
        "thon",
        "tibetan water drum",
        "ti bwa",
        "tiêu",
        "timbales",
        "time",
        "timpani",
        "tin whistle",
        "tinya",
        "tiple",
        "tololoche",
        "tom-tom",
        "tonkori",
        "topshuur",
        "toy piano",
        "tràm plè",
        "trắng jâu",
        "trắng lu",
        "translated",
        "transliterated",
        "transverse flute",
        "treble",
        "tres",
        "triangle",
        "tromba marina",
        "trombone",
        "tromboon",
        "trống bông",
        "trumpet",
        "t'rưng",
        "tuba",
        "tubax",
        "tubon",
        "tubular bells",
        "tumbi",
        "tuned percussion",
        "turkish baglama",
        "turntable(s)",
        "txalaparta",
        "typewriter",
        "tzoura",
        "udu",
        "uilleann pipes",
        "ukeke",
        "ukulele",
        "upright piano",
        "ütőgardon",
        "vacuum cleaner",
        "valiha",
        "valved brass instruments",
        "valve trombone",
        "venu",
        "vessel drum",
        "vessel flute",
        "vibraphone",
        "vibraslap",
        "vichitra veena",
        "vielle",
        "vienna horn",
        "vietnamese guitar",
        "viola",
        "violin",
        "violoncello piccolo",
        "violone",
        "violotta",
        "virginal",
        "vocal",
        "vocals",
        "vocoder",
        "voice synthesizer",
        "wagner tuba",
        "warr guitar",
        "washboard",
        "washtub bass",
        "waterphone",
        "wavedrum",
        "whip",
        "whistle",
        "willow flute",
        "wind chime",
        "wind instruments",
        "wire-strung harp",
        "wood block",
        "wooden fish",
        "woodwind",
        "wot",
        "wurlitzer electric piano",
        "xalam",
        "xaphoon",
        "xiao",
        "xiaoluo",
        "xun",
        "xylophone",
        "xylorimba",
        "yangqin",
        "yatga",
        "yaylı tanbur",
        "yehu",
        "yonggo",
        "yueqin",
        "zabumba",
        "żafżafa",
        "żaqq",
        "zarb",
        "zhaleika",
        "zhonghu",
        "zhongruan",
        "zill",
        "zither",
        "żummara",
        "zurna"
    )

    fun isKey(key: String): Boolean = musicianCredits.contains(key)
}